language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.10"

branches:
    only:
        - develop

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install libdb-dev"

notifications:
    email: false

env: PERL_CPANM_OPT="--notest"

after_success:
    cover -report coveralls
